name: The Nobel Prize Winners Network
description: This website is the final project for the course Social Graphs and Interactions
title: The Nobel Prize Winners Network
theme: jekyll-theme-cayman
url: https://fontaluc.github.io/Nobel/
markdown: kramdown
kramdown:
#  parse_block_html: true
#escape_markup: false 
#baseurl: /Nobel
