name: The Nobel Prize Laureates Network
description: This webpage was created by Lucie Fontaine, Milad Taghikhani and Charidimos Vradis as part of the final project for the course Social Graphs and Interactions at DTU
title: The Nobel Prize Laureates Network
theme: jekyll-theme-cayman
url: https://fontaluc.github.io/Nobel/
markdown: kramdown
kramdown:
  parse_block_html: true
#escape_markup: false 
#baseurl: /Nobel
